version: "3"
services:
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-local.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      # - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      # - "4317:4317"  # otlp grpc
      # - "4318:4318"  # otlp http
      # - "9411:9411"   # zipkin
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tempoBackendSearch tempoServiceGraph

  jaeger:
    image: jaegertracing/all-in-one:1.6
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411 COLLECTOR_OTLP_ENABLED=true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  # synthetic-load-generator:
  #   image: omnition/synthetic-load-generator:1.0.25
  #   volumes:
  #     - ./load-generator.json:/etc/load-generator.json
  #   environment:
  #     - TOPOLOGY_FILE=/etc/load-generator.json
  #     - JAEGER_COLLECTOR_URL=http://tempo:14268
  #   depends_on:
  #     - tempo

  prometheus:
    image: prom/prometheus:v2.36.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.0.0-beta1
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

  tracing-example:
    image: tracing-example
    ports:
      - 8000:8000
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    depends_on:
      - tempo
      - loki

  tracing-example-jaeger:
    image: tracing-example-jaeger
    ports:
      - 8001:8001
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    depends_on:
      - jaeger
      - loki

  loki:
    image: grafana/loki:2.5.0
    command: -config.file=/etc/loki/local-config.yaml
    ports:
    - "3100:3100"
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/api/prom/push'
